<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>EnterEmail</name>
   <tag></tag>
   <elementGuidId>8f693b57-376f-4b70-a2b3-827415837c1e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>XPATH</name>
      <type>Main</type>
      <value>(//*[@class='android.widget.EditText'])[1]</value>
      <webElementGuid>8d623ef7-535f-4907-9ebd-6d589365cf44</webElementGuid>
   </webElementProperties>
   <locator>(//*[@class='android.widget.EditText'])[1]</locator>
   <locatorStrategy>XPATH</locatorStrategy>
</MobileElementEntity>
