<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>InputPassword</name>
   <tag></tag>
   <elementGuidId>66d0a40a-1e2a-4eed-8584-ee82fd3c0c9d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>XPATH</name>
      <type>Main</type>
      <value>(//*[@class='android.widget.EditText'])[2]</value>
      <webElementGuid>8848f6ac-482d-44e1-a5b4-25187e200ca1</webElementGuid>
   </webElementProperties>
   <locator>(//*[@class='android.widget.EditText'])[2]</locator>
   <locatorStrategy>XPATH</locatorStrategy>
</MobileElementEntity>
