<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>RegisterNewCheckbox</name>
   <tag></tag>
   <elementGuidId>6e0c6068-f9b3-409a-9c02-647329845595</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>XPATH</name>
      <type>Main</type>
      <value>(//*[@class='android.widget.CheckBox'])[2]</value>
      <webElementGuid>4b44a7ad-9394-4053-bbf0-1e7f7b103525</webElementGuid>
   </webElementProperties>
   <locator>(//*[@class='android.widget.CheckBox'])[2]</locator>
   <locatorStrategy>XPATH</locatorStrategy>
</MobileElementEntity>
